os: osx
osx_image: xcode11.4
script:
  - xcodebuild clean build test -workspace Jointify.xcworkspace -scheme Jointify -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.4.1,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
